name       : sof-firmware
version    : '1.8'
release    : 1
source     :
    - https://github.com/thesofproject/sof-bin/releases/download/v1.8/sof-bin-v1.8.tar.gz : cc9ed7b24a892c8b16ac95e0f12d3d6ddab1d71758060c73d1296803dc4e8cff
license    :
    - BSD-3-Clause
    - ISC
component  : kernel
summary    : Sound Open Firmware
description: |
    Sound Open Firmware
install    : |
    install -dm00755 $installdir/lib/firmware
    cp -a sof-v$version "$installdir/lib/firmware/sof"
    cp -a sof-tplg-v$version "$installdir/lib/firmware/sof-tplg"
