name       : sof-firmware
version    : 2.1.1
release    : 6
source     :
    - https://github.com/thesofproject/sof-bin/releases/download/v2.1.1/sof-bin-v2.1.1.tar.gz : adcd22ba2f2aad911fdc53c478187bc6ddb9174fa52fa43ba07f6f0cc8d12a19
license    :
    - BSD-3-Clause
    - ISC
component  : kernel
summary    : Sound Open Firmware
description: |
    Sound Open Firmware
install    : |
    install -dm00755 $installdir/lib/firmware/intel
    cp -a sof-v$version "$installdir/lib/firmware/intel/sof"
    cp -a sof-tplg-v$version "$installdir/lib/firmware/intel/sof-tplg"
