name       : sof-firmware
version    : '2.2'
release    : 7
source     :
    - https://github.com/thesofproject/sof-bin/releases/download/v2.2/sof-bin-v2.2.tar.gz : f0a22018aa02266e3713f1551b698847ca303859be4be8c711dd3685de55ad15
license    :
    - BSD-3-Clause
    - ISC
component  : kernel
summary    : Sound Open Firmware
description: |
    Sound Open Firmware
install    : |
    install -dm00755 $installdir/lib/firmware/intel
    cp -a sof-v$version "$installdir/lib/firmware/intel/sof"
    cp -a sof-tplg-v$version "$installdir/lib/firmware/intel/sof-tplg"
