name       : sof-firmware
version    : '2.0'
release    : 5
source     :
    - https://github.com/thesofproject/sof-bin/releases/download/v2.0/sof-bin-v2.0.tar.gz : 80a245ba59ba826e4394206e39f4d7049e2bea139583e97923c7fbb8411ce922
license    :
    - BSD-3-Clause
    - ISC
component  : kernel
summary    : Sound Open Firmware
description: |
    Sound Open Firmware
install    : |
    install -dm00755 $installdir/lib/firmware/intel
    cp -a sof-v$version "$installdir/lib/firmware/intel/sof"
    cp -a sof-tplg-v$version "$installdir/lib/firmware/intel/sof-tplg"
