name       : sof-firmware
version    : 1.9.3
release    : 4
source     :
    - https://github.com/thesofproject/sof-bin/releases/download/v1.9.3/sof-bin-v1.9.3.tar.gz : 8188edc8929dbf7a0c527a451503f4b2af71137a8479f71be1852fad49dc5ba3
license    :
    - BSD-3-Clause
    - ISC
component  : kernel
summary    : Sound Open Firmware
description: |
    Sound Open Firmware
install    : |
    install -dm00755 $installdir/lib/firmware/intel
    cp -a sof-v$version "$installdir/lib/firmware/intel/sof"
    cp -a sof-tplg-v$version "$installdir/lib/firmware/intel/sof-tplg"
